### ISSUE TITLE
Create key when it does not exists instead of failing (yaml-cli v0.0.3)

### ISSUE THREAD

**Issue by carnei-ro** [4e4o/yaml-cli#2]
example yaml:

```yaml
system:
  logLevel: TRACE
  updateChannel: stable
  buffer: 1024
isp:
...
```

I want to do `yaml-cli -i my-yaml.yaml -s .system.webPort 80` and the result would be:

```yaml
system:
  logLevel: TRACE
  updateChannel: stable
  buffer: 1024
  webPort: 80
isp:
...
```

But the yaml-cli crashes returning error code 1
